services:
    game-data:
        image: redis:7-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass test
        volumes:
            - game-data:/data

    user-data:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env_file:
          - .env
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
          - user-data:/var/lib/postgresql/data/

volumes:
  game-data:
    driver: local
  user-data:
    driver: local