services:
    game_data:
        image: redis/redis-stack:latest
        restart: always
        ports:
            - '6379:6379'
            - '8001:8001'
        volumes:
            - game_data:/data

    user_data:
        image: postgres:14-alpine
        ports:
            - "5432:5432"
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - user_data:/var/lib/postgresql/data/

volumes:
    game_data:
        driver: local
    user_data:
        driver: local